### ISSUE TITLE
[Design] Drop support to Node 8, 10 and 12

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-wallet-headless#168]
# Summary

We want to take actions to make sure the project is compatible with Node.js versions 14 and 16, and make sure nobody is using versions 8, 10 and 12 of Node.js to run the wallet-headless. Minimum recommended will be v14.

## Motivation
Versions 8 and 10 are already out of support, and 12 will be soon (Apr/2022)
https://nodejs.org/en/about/releases/

They don't receive security updates anymore.

# Task Breakdown
- Run the QA with Node.js v14 and v16 - 0.2
     - [x] v14
     - [x] v16
- [x] Migrate the Docker image to Node.js v16 - 0.1
- [x] Migrate the CI jobs to v14 and v16 - 0.1
- [x] Run the integration tests with v14 and v16 - 0.1
- [x] Set a minimum version for Node.js in package.json (like in https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json) - 0.1
- [ ] Update documentation, make announcements where needed and talk to the partners

**Comment by msbrogli** [comment]
Approved.
